name: directory
description: A game created with the Crossbow game engine.

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  crossbow_backend:
    git:
      url: https://github.com/chrisnorman7/crossbow
      path: crossbow_backend
